CLASS zcl_day8 DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    CLASS-METHODS part1 IMPORTING use_sample    TYPE abap_bool OPTIONAL
                        RETURNING VALUE(result) TYPE int8.

    CLASS-METHODS part2 IMPORTING use_sample    TYPE abap_bool OPTIONAL
                        RETURNING VALUE(result) TYPE int8.

    INTERFACES if_oo_adt_classrun.

  PRIVATE SECTION.
    CLASS-METHODS get_puzzle_sample1 RETURNING VALUE(result) TYPE string_table.
    CLASS-METHODS get_puzzle_sample2 RETURNING VALUE(result) TYPE string_table.
    CLASS-METHODS get_puzzle_input   RETURNING VALUE(result) TYPE string_table.
ENDCLASS.


CLASS zcl_day8 IMPLEMENTATION.
  METHOD if_oo_adt_classrun~main.
    DATA(result1) = zcl_day8=>part1( ).
    out->write( name = |Steps required to reach ZZZ:|
                data = result1 ).

    DATA(result2) = zcl_day8=>part2( ).
    out->write( name = |Steps before you're only on nodes that end with Z:|
                data = result2 ).
  ENDMETHOD.

  METHOD part1.
    TYPES: BEGIN OF node,
             name  TYPE c LENGTH 3,
             left  TYPE c LENGTH 3,
             right TYPE c LENGTH 3,
           END OF node.

    DATA(input) = COND string_table( WHEN use_sample = abap_true THEN get_puzzle_sample1( ) ELSE get_puzzle_input( ) ).
    DATA(instructions) = input[ 1 ].

    DATA nodes TYPE SORTED TABLE OF node WITH UNIQUE KEY name.
    nodes = VALUE #( FOR <line> IN input FROM 3
                     ( name = <line>+0(3) left = <line>+7(3) right = <line>+12(3) ) ).
    DATA(node) = nodes[ 1 ].
    DO.
      DATA(offset) = result MOD strlen( instructions ).
      DATA(direction) = instructions+offset(1).
      IF direction = 'L'.
        node = nodes[ name = node-left ].
      ELSE.
        node = nodes[ name = node-right ].
      ENDIF.
      result = result + 1.
      IF node-name = 'ZZZ'.
        EXIT.
      ENDIF.
    ENDDO.
    WRITE / |{ result } steps are required to reach ZZZ.|.
  ENDMETHOD.

  METHOD part2.
    TYPES: BEGIN OF node,
             name  TYPE c LENGTH 3,
             left  TYPE c LENGTH 3,
             right TYPE c LENGTH 3,
           END OF node.

    DATA(input) = COND string_table( WHEN use_sample = abap_true THEN get_puzzle_sample2( ) ELSE get_puzzle_input( ) ).
    DATA(instructions) = input[ 1 ].

    DATA nodes TYPE SORTED TABLE OF node WITH UNIQUE KEY name.
    nodes = VALUE #( FOR <line> IN input FROM 3
                     ( name = <line>+0(3) left = <line>+7(3) right = <line>+12(3) ) ).

    result = 1.
    LOOP AT nodes INTO DATA(node) WHERE name+2(1) = 'A'.
      DATA(step) = 0.
      WHILE NOT node-name+2(1) = 'Z'.
        DATA(offset) = step MOD strlen( instructions ).
        DATA(direction) = instructions+offset(1).
        IF direction = 'L'.
          node = nodes[ name = node-left ].
        ELSE.
          node = nodes[ name = node-right ].
        ENDIF.
        step = step + 1.
      ENDWHILE.

      DATA(num1) = result.
      DATA(num2) = step.
      WHILE num2 > 0.
        DATA(temp) = num2.
        num2 = num1 MOD num2.
        num1 = temp.
      ENDWHILE.
      DATA(gcd) = num1.

      result = result * step / gcd.
    ENDLOOP.
    WRITE / |{ result } steps does it take before you're only on nodes that end with Z.|.
  ENDMETHOD.

  METHOD get_puzzle_sample1.
    SPLIT
|LLR\n\n| &&
|AAA = (BBB, BBB)\n| &&
|BBB = (AAA, ZZZ)\n| &&
|ZZZ = (ZZZ, ZZZ)\n| AT |\n| INTO TABLE result.
  ENDMETHOD.

  METHOD get_puzzle_sample2.
    SPLIT
|LR\n\n| &&
|11A = (11B, XXX)\n| &&
|11B = (XXX, 11Z)\n| &&
|11Z = (11B, XXX)\n| &&
|22A = (22B, XXX)\n| &&
|22B = (22C, 22C)\n| &&
|22C = (22Z, 22Z)\n| &&
|22Z = (22B, 22B)\n| &&
|XXX = (XXX, XXX)\n| AT |\n| INTO TABLE result.
  ENDMETHOD.

  METHOD get_puzzle_input.
    SPLIT
|LLRLRRRLRRRLRRLLRRRLLRRLLRLRLRRRLRRRLLRRRLLRRRLRRLRRLRLRRLLRRRLRRRLLRRRLRRLLLRRLRLLLRLRRRLRLRLLLRRLRRLLLRRRLLRRRLRLRLLRRLRLRRRLRLRLLRL| &&
|RRLRRRLRRLRLRRRLRLRRLRRLRLRRLLRLRLRRLRLLRRLRRLRLRRLLRLRLLRRLLRLLLRRLRLRRRLRRRLRRRLRLRLRRRLLLRLRRLRLRRRLRRRLRRRLRLRRRLRRRLRRRLRRRR\n\n| &&
|GLR = (SPQ, LKJ)\n| &&
|LDM = (LXK, RMT)\n| &&
|NTJ = (NGP, PKQ)\n| &&
|PXL = (GQG, CCL)\n| &&
|TMB = (SSN, LVM)\n| &&
|XNP = (SXR, XJH)\n| &&
|SSG = (VJT, BPK)\n| &&
|XVS = (GHQ, LCJ)\n| &&
|HRM = (GNJ, GNJ)\n| &&
|NNG = (GCB, FXT)\n| &&
|VLL = (NTJ, LFV)\n| &&
|SXX = (SFQ, TQR)\n| &&
|XNM = (JCQ, MNT)\n| &&
|XTR = (JGP, GPS)\n| &&
|LXN = (DKT, GBC)\n| &&
|HGN = (GPH, GFD)\n| &&
|JJF = (DSH, DVT)\n| &&
|BTJ = (SDH, CLJ)\n| &&
|DPV = (RSQ, XGJ)\n| &&
|MMK = (CXD, KNV)\n| &&
|FXT = (LDV, VBP)\n| &&
|HDL = (RVD, JQG)\n| &&
|GPX = (PFH, XBR)\n| &&
|FMJ = (LJF, KPC)\n| &&
|CRX = (XXN, XNQ)\n| &&
|TQN = (JJF, SBZ)\n| &&
|FGB = (JHR, QGC)\n| &&
|HFQ = (PJS, FPN)\n| &&
|BKS = (GCK, TRC)\n| &&
|VPS = (BRP, BSL)\n| &&
|JMV = (QQM, JVV)\n| &&
|LMF = (DQJ, RQP)\n| &&
|TDT = (KVD, KNT)\n| &&
|PFP = (SMV, NXN)\n| &&
|DKT = (NCT, MPG)\n| &&
|NGP = (LMP, LBG)\n| &&
|BPD = (HRM, HRM)\n| &&
|CFK = (HDM, JSV)\n| &&
|CLB = (PXL, CVB)\n| &&
|GHG = (XVM, BGM)\n| &&
|GCB = (LDV, VBP)\n| &&
|NSH = (SHX, JTQ)\n| &&
|GGR = (STX, HHQ)\n| &&
|VTX = (XSM, TNV)\n| &&
|JGB = (QTG, TBL)\n| &&
|RDJ = (QQQ, NGC)\n| &&
|KVL = (MBG, CDD)\n| &&
|LVM = (KLR, KVT)\n| &&
|FRV = (XRD, CGJ)\n| &&
|VMJ = (DDG, GQC)\n| &&
|FDA = (BKF, MQC)\n| &&
|DSC = (QRC, FMJ)\n| &&
|CRQ = (GKT, RMR)\n| &&
|QLC = (HHT, HLQ)\n| &&
|FSN = (LHJ, XTT)\n| &&
|RDP = (CNJ, SQD)\n| &&
|XRJ = (MCV, MVT)\n| &&
|KJD = (JRX, JCM)\n| &&
|PXJ = (JGH, CMB)\n| &&
|FCQ = (XKQ, MFB)\n| &&
|FXK = (MSB, TVD)\n| &&
|JNF = (TQR, SFQ)\n| &&
|CJJ = (PXJ, QQJ)\n| &&
|KNV = (FTH, RFL)\n| &&
|HFH = (CBP, DPN)\n| &&
|LHT = (PGK, DLD)\n| &&
|GLC = (DTJ, BDD)\n| &&
|PNH = (SSG, QGT)\n| &&
|PJS = (FHQ, GBD)\n| &&
|NQJ = (XSD, KKD)\n| &&
|XVL = (PGN, KSB)\n| &&
|FMM = (CKQ, FVF)\n| &&
|NFL = (BPV, HGF)\n| &&
|PJR = (SNT, HBM)\n| &&
|JQG = (XNM, QKN)\n| &&
|NGQ = (NMV, NBS)\n| &&
|CQV = (MXC, DQR)\n| &&
|HQJ = (GGR, VCX)\n| &&
|TTQ = (HLJ, MVF)\n| &&
|HNR = (JGP, GPS)\n| &&
|LRK = (NFL, LGC)\n| &&
|GML = (TSF, HFT)\n| &&
|NLV = (JQS, HHF)\n| &&
|VGR = (VQT, DRX)\n| &&
|TQR = (SXH, QJP)\n| &&
|HPC = (PTF, RRH)\n| &&
|KCN = (PQP, VBQ)\n| &&
|HTF = (VGR, TTS)\n| &&
|QKH = (DCP, KNL)\n| &&
|HHH = (PJR, RSP)\n| &&
|QMD = (FNP, CCG)\n| &&
|LGV = (LTB, JST)\n| &&
|KQX = (SPF, MLD)\n| &&
|PJX = (MMP, RHG)\n| &&
|QRD = (GDL, BBQ)\n| &&
|CCG = (PVB, GBB)\n| &&
|CPG = (KSD, BXG)\n| &&
|PFV = (PMX, RHS)\n| &&
|VCC = (RPQ, RDD)\n| &&
|CVF = (XSM, TNV)\n| &&
|QQX = (HGN, GDF)\n| &&
|QVJ = (HXJ, GTV)\n| &&
|PSD = (CQD, QFD)\n| &&
|DLP = (QQX, SQR)\n| &&
|HBM = (MCR, XVP)\n| &&
|SFS = (BTS, TSC)\n| &&
|NKN = (GBQ, RSF)\n| &&
|VQT = (BTJ, FGM)\n| &&
|XBH = (RMT, LXK)\n| &&
|SRM = (PGK, DLD)\n| &&
|FKQ = (SRV, PCC)\n| &&
|LSX = (XVS, HMG)\n| &&
|CLL = (NXN, SMV)\n| &&
|GDD = (NLD, TGL)\n| &&
|RVD = (XNM, QKN)\n| &&
|RHG = (BJM, NBR)\n| &&
|KFX = (FMJ, QRC)\n| &&
|FGM = (CLJ, SDH)\n| &&
|XJJ = (CVF, VTX)\n| &&
|NHL = (XBJ, HLF)\n| &&
|VMS = (VVQ, PPC)\n| &&
|JCQ = (CFP, FGB)\n| &&
|PSP = (VTH, HDC)\n| &&
|LRQ = (GDG, VBL)\n| &&
|PKL = (SSG, QGT)\n| &&
|LHJ = (HML, JMG)\n| &&
|BDX = (FMK, XDS)\n| &&
|DPX = (BBF, SBK)\n| &&
|GFD = (XVV, CHS)\n| &&
|PSR = (FPP, DSL)\n| &&
|HQB = (MRL, DHG)\n| &&
|GKD = (SSP, JSP)\n| &&
|TKL = (KBV, GTH)\n| &&
|HMF = (HHT, HLQ)\n| &&
|DGS = (VDJ, TJN)\n| &&
|MRQ = (QVM, KJC)\n| &&
|XSD = (TGJ, BDS)\n| &&
|GDG = (RGS, HFH)\n| &&
|JSV = (MFD, HXP)\n| &&
|HMG = (LCJ, GHQ)\n| &&
|BPV = (MRQ, XRL)\n| &&
|SSP = (KQM, NSX)\n| &&
|SDH = (QQR, RGR)\n| &&
|JTX = (NHL, TST)\n| &&
|NBR = (BXP, LSX)\n| &&
|PCN = (JGR, PQQ)\n| &&
|QCR = (RQV, FRV)\n| &&
|NPH = (HHH, MXN)\n| &&
|CBS = (PMX, RHS)\n| &&
|JNR = (HKQ, XHG)\n| &&
|GKT = (HRC, KHL)\n| &&
|CDX = (NXJ, FVH)\n| &&
|MXN = (RSP, PJR)\n| &&
|ZZZ = (VBQ, PQP)\n| &&
|MSD = (VVQ, PPC)\n| &&
|SMV = (VKQ, JNR)\n| &&
|KKJ = (PGN, KSB)\n| &&
|RJC = (CNM, LGB)\n| &&
|QFB = (QQS, TMC)\n| &&
|STX = (KMP, KMP)\n| &&
|QQR = (XTR, HNR)\n| &&
|BPA = (DSH, DVT)\n| &&
|GDT = (XVD, DNS)\n| &&
|KXM = (CNJ, SQD)\n| &&
|CHL = (LBP, PJX)\n| &&
|XQX = (CMN, QXH)\n| &&
|GQG = (BKS, VPQ)\n| &&
|HRC = (VCR, NPH)\n| &&
|LSL = (FMM, JTP)\n| &&
|DDQ = (XPS, DMJ)\n| &&
|DMF = (DHG, MRL)\n| &&
|HBP = (KQX, CDN)\n| &&
|DSR = (QMD, PBN)\n| &&
|SJD = (VGP, KSG)\n| &&
|PQQ = (KKJ, XVL)\n| &&
|XQG = (LQK, GXD)\n| &&
|QGT = (VJT, BPK)\n| &&
|KDF = (LHG, LHG)\n| &&
|VQV = (CGG, HVC)\n| &&
|VJT = (XKS, CLB)\n| &&
|TBL = (JSG, XDL)\n| &&
|TCC = (DVX, KMN)\n| &&
|SHP = (QRD, HDF)\n| &&
|CRD = (FXQ, TVC)\n| &&
|TQP = (FQN, BNF)\n| &&
|JVV = (VMJ, VJS)\n| &&
|LKJ = (KNP, GHG)\n| &&
|DTR = (KHX, GQK)\n| &&
|FXR = (GDT, GLK)\n| &&
|DLD = (LBV, TMB)\n| &&
|PNV = (BMP, LLQ)\n| &&
|TMC = (FQV, PPS)\n| &&
|VCR = (MXN, HHH)\n| &&
|QSR = (DCP, KNL)\n| &&
|NVT = (GNR, FKQ)\n| &&
|JHM = (NLH, KQR)\n| &&
|LBG = (TCC, RRN)\n| &&
|PBK = (XBM, RJL)\n| &&
|CGD = (PQQ, JGR)\n| &&
|LHG = (JJF, JJF)\n| &&
|FMD = (LGC, NFL)\n| &&
|XJH = (LMF, SMX)\n| &&
|CNM = (VBN, LGV)\n| &&
|PPS = (NLV, VJR)\n| &&
|GNN = (VQV, PLF)\n| &&
|DXD = (SXR, XJH)\n| &&
|VPQ = (GCK, TRC)\n| &&
|KSB = (FSX, RJC)\n| &&
|CQH = (VCC, RGM)\n| &&
|DQV = (CBM, JGF)\n| &&
|JPG = (MMQ, DLP)\n| &&
|PNT = (BMB, TCS)\n| &&
|MVF = (MNN, DFP)\n| &&
|XVD = (PVR, CFK)\n| &&
|DQR = (MBF, FCQ)\n| &&
|HLF = (GGF, JPG)\n| &&
|CFJ = (DPX, MHN)\n| &&
|MDF = (LRK, FMD)\n| &&
|GQT = (JTL, QRJ)\n| &&
|KKR = (CJG, LST)\n| &&
|BKF = (HDL, GCP)\n| &&
|HGF = (XRL, MRQ)\n| &&
|MCR = (CRR, BLQ)\n| &&
|GVD = (BKF, MQC)\n| &&
|JSG = (QRG, BCL)\n| &&
|RQK = (XNQ, XXN)\n| &&
|NXF = (NGQ, JSQ)\n| &&
|RDD = (XNR, LVG)\n| &&
|QJP = (GRS, QKX)\n| &&
|RCL = (MDC, FJM)\n| &&
|LXK = (CVG, BDX)\n| &&
|KNP = (XVM, BGM)\n| &&
|MPG = (NBF, KRK)\n| &&
|CCL = (VPQ, BKS)\n| &&
|SSN = (KVT, KLR)\n| &&
|QRK = (FKH, VFD)\n| &&
|QQS = (PPS, FQV)\n| &&
|CHS = (NJX, QRK)\n| &&
|PVL = (JRX, JCM)\n| &&
|KNF = (HXJ, GTV)\n| &&
|FKH = (CSV, JHP)\n| &&
|XDK = (XQX, VHT)\n| &&
|JKR = (MDR, NKN)\n| &&
|DMJ = (KQL, BRM)\n| &&
|KBV = (DSC, KFX)\n| &&
|BRM = (BPD, NCB)\n| &&
|SNT = (MCR, XVP)\n| &&
|CFP = (JHR, QGC)\n| &&
|TJF = (SRH, SLM)\n| &&
|LMP = (TCC, RRN)\n| &&
|CDM = (CVF, VTX)\n| &&
|GQK = (NVT, TSJ)\n| &&
|RGM = (RPQ, RDD)\n| &&
|BLF = (HDC, VTH)\n| &&
|PGS = (JRH, DPV)\n| &&
|LCX = (QCD, XQG)\n| &&
|GKM = (GLB, CJJ)\n| &&
|GFB = (QCF, VNT)\n| &&
|VQM = (PJP, PJP)\n| &&
|HKH = (SHP, GCC)\n| &&
|STG = (GNN, VPZ)\n| &&
|SBF = (KCN, ZZZ)\n| &&
|KRK = (TTQ, CGX)\n| &&
|VRF = (GLC, NXP)\n| &&
|JFP = (QHG, RDJ)\n| &&
|HDC = (SML, HPC)\n| &&
|TPB = (GNJ, SBF)\n| &&
|DDG = (DLT, KBM)\n| &&
|QTM = (KDL, DVR)\n| &&
|SJG = (NXJ, FVH)\n| &&
|RTT = (QCF, VNT)\n| &&
|GTV = (DMX, GFN)\n| &&
|SBK = (DJD, VFS)\n| &&
|XVP = (BLQ, CRR)\n| &&
|LXP = (TQP, BBX)\n| &&
|CMB = (PVL, KJD)\n| &&
|VHT = (QXH, CMN)\n| &&
|SMR = (LST, CJG)\n| &&
|BXG = (XBF, XFD)\n| &&
|GXD = (NPV, HBP)\n| &&
|BVA = (SMR, KKR)\n| &&
|XRD = (SQN, MVX)\n| &&
|CNJ = (BMK, RPT)\n| &&
|QFR = (LRK, FMD)\n| &&
|FPP = (NCR, VPS)\n| &&
|NQN = (LBP, PJX)\n| &&
|PLF = (CGG, HVC)\n| &&
|TPK = (VQM, VQM)\n| &&
|MKK = (MTJ, PSD)\n| &&
|PFB = (MXP, LGF)\n| &&
|VDJ = (LSL, QVX)\n| &&
|FVH = (JXQ, PBK)\n| &&
|HDM = (HXP, MFD)\n| &&
|VJS = (DDG, GQC)\n| &&
|PHC = (KDF, TCB)\n| &&
|VFD = (CSV, JHP)\n| &&
|RRH = (GDD, XDM)\n| &&
|MRL = (GML, DLB)\n| &&
|CDD = (JDK, KJQ)\n| &&
|XPS = (KQL, BRM)\n| &&
|NXH = (JMV, PVK)\n| &&
|NJX = (FKH, VFD)\n| &&
|FQL = (DSL, FPP)\n| &&
|LST = (QDF, JDR)\n| &&
|PQP = (LHT, SRM)\n| &&
|LPS = (PTK, PHC)\n| &&
|CVT = (CXD, KNV)\n| &&
|QTG = (XDL, JSG)\n| &&
|FXQ = (FGC, QBT)\n| &&
|TRK = (SSQ, LPX)\n| &&
|PTK = (KDF, KDF)\n| &&
|BXP = (HMG, XVS)\n| &&
|GCK = (QVJ, KNF)\n| &&
|MSB = (QKR, NQJ)\n| &&
|SVN = (DPV, JRH)\n| &&
|CQD = (PST, DQV)\n| &&
|QBQ = (TNG, PNT)\n| &&
|HJZ = (MQC, BKF)\n| &&
|HPT = (GDG, VBL)\n| &&
|TJN = (QVX, LSL)\n| &&
|NDA = (VQV, PLF)\n| &&
|JHP = (XRJ, VKF)\n| &&
|QTP = (XTT, LHJ)\n| &&
|JTL = (GVD, GVD)\n| &&
|DDV = (NDJ, NVK)\n| &&
|SCF = (VCC, RGM)\n| &&
|RGL = (NSH, TMK)\n| &&
|KSD = (XBF, XFD)\n| &&
|RJL = (TPK, BVS)\n| &&
|QKX = (NPC, PPG)\n| &&
|XMR = (TBL, QTG)\n| &&
|CVG = (FMK, XDS)\n| &&
|SKS = (SVQ, THL)\n| &&
|CCM = (MXP, LGF)\n| &&
|TNG = (TCS, BMB)\n| &&
|XXN = (GLR, QQK)\n| &&
|NVK = (VRF, PMC)\n| &&
|RRN = (DVX, KMN)\n| &&
|NPC = (LJH, LJH)\n| &&
|JJL = (XBH, LDM)\n| &&
|LDV = (FXK, DMP)\n| &&
|KMP = (JTL, JTL)\n| &&
|QNQ = (RMR, GKT)\n| &&
|JXQ = (XBM, RJL)\n| &&
|CBP = (NQN, CHL)\n| &&
|PPG = (LJH, XTG)\n| &&
|LQK = (HBP, NPV)\n| &&
|XTT = (HML, JMG)\n| &&
|SVQ = (PKL, PNH)\n| &&
|DSL = (NCR, VPS)\n| &&
|LTB = (FKX, DTR)\n| &&
|NLH = (GFB, RTT)\n| &&
|QFD = (PST, DQV)\n| &&
|RHS = (SNV, HPJ)\n| &&
|JPT = (GCS, VGX)\n| &&
|VTH = (HPC, SML)\n| &&
|JRF = (LNR, HSF)\n| &&
|BPK = (CLB, XKS)\n| &&
|LHH = (RDP, KXM)\n| &&
|TKP = (DQF, CXL)\n| &&
|XVV = (NJX, QRK)\n| &&
|GBD = (MBC, QBQ)\n| &&
|PBP = (DDV, THT)\n| &&
|TNF = (KNT, KVD)\n| &&
|RFL = (VMX, DBF)\n| &&
|MBC = (TNG, PNT)\n| &&
|MCV = (VDS, PBP)\n| &&
|GNR = (PCC, SRV)\n| &&
|DHG = (GML, DLB)\n| &&
|TCV = (LDF, TKL)\n| &&
|XDS = (PSR, FQL)\n| &&
|VMR = (TST, NHL)\n| &&
|XVM = (RGK, QFB)\n| &&
|LJN = (MXC, DQR)\n| &&
|VBL = (HFH, RGS)\n| &&
|LCG = (PFV, CBS)\n| &&
|SXR = (LMF, SMX)\n| &&
|TGL = (VMR, JTX)\n| &&
|BDS = (QKH, QSR)\n| &&
|RGS = (CBP, DPN)\n| &&
|RFZ = (KKR, SMR)\n| &&
|JTQ = (DSR, BQJ)\n| &&
|BQJ = (QMD, PBN)\n| &&
|VVQ = (DGS, GSN)\n| &&
|CGG = (NNL, LCR)\n| &&
|CVH = (LPX, SSQ)\n| &&
|NGC = (GKM, TTN)\n| &&
|XNR = (XNP, DXD)\n| &&
|FBN = (DQF, CXL)\n| &&
|MBG = (KJQ, JDK)\n| &&
|JSQ = (NMV, NBS)\n| &&
|LRF = (VJM, MQQ)\n| &&
|GBC = (NCT, MPG)\n| &&
|NXP = (BDD, DTJ)\n| &&
|LGC = (BPV, HGF)\n| &&
|HDF = (BBQ, GDL)\n| &&
|RSF = (JPT, SCP)\n| &&
|LDF = (KBV, GTH)\n| &&
|QQJ = (CMB, JGH)\n| &&
|SHX = (DSR, BQJ)\n| &&
|RSP = (SNT, HBM)\n| &&
|GPH = (CHS, XVV)\n| &&
|DQJ = (QNQ, CRQ)\n| &&
|MMQ = (SQR, QQX)\n| &&
|FVF = (PCN, CGD)\n| &&
|BBF = (VFS, DJD)\n| &&
|QBT = (HFQ, PGM)\n| &&
|RPQ = (XNR, LVG)\n| &&
|CJG = (QDF, JDR)\n| &&
|SBR = (MSD, VMS)\n| &&
|SXH = (GRS, QKX)\n| &&
|MFB = (JTF, QTM)\n| &&
|DBL = (XBR, PFH)\n| &&
|TGJ = (QSR, QKH)\n| &&
|CXL = (KMK, RVR)\n| &&
|PGM = (FPN, PJS)\n| &&
|NMR = (HXM, TJF)\n| &&
|QGC = (STV, NJT)\n| &&
|VMX = (GTG, QCR)\n| &&
|DSH = (CRX, RQK)\n| &&
|PST = (CBM, JGF)\n| &&
|JVR = (PVK, JMV)\n| &&
|GRS = (NPC, NPC)\n| &&
|RBT = (MHN, DPX)\n| &&
|XBF = (XQL, BVB)\n| &&
|DJD = (CFF, JJL)\n| &&
|GLB = (PXJ, QQJ)\n| &&
|MQC = (HDL, GCP)\n| &&
|SHC = (BKK, STG)\n| &&
|JGH = (PVL, KJD)\n| &&
|XHG = (VVS, HTD)\n| &&
|SPF = (XMR, JGB)\n| &&
|GHV = (BLF, PSP)\n| &&
|VGN = (KSG, VGP)\n| &&
|FQV = (NLV, VJR)\n| &&
|HHR = (LJN, CQV)\n| &&
|GFN = (FHL, SHC)\n| &&
|KJQ = (NXH, JVR)\n| &&
|CFF = (XBH, LDM)\n| &&
|SFQ = (SXH, QJP)\n| &&
|XBR = (CQH, SCF)\n| &&
|XND = (DMJ, XPS)\n| &&
|LDQ = (BXG, KSD)\n| &&
|CMN = (PFP, CLL)\n| &&
|GCC = (HDF, QRD)\n| &&
|HPJ = (PMP, FRM)\n| &&
|BSS = (MKK, TVJ)\n| &&
|VTC = (DKR, MXS)\n| &&
|VCX = (STX, HHQ)\n| &&
|RQV = (XRD, CGJ)\n| &&
|PGK = (TMB, LBV)\n| &&
|HTD = (LRF, KXL)\n| &&
|PVR = (JSV, HDM)\n| &&
|BBQ = (XKC, HHR)\n| &&
|PKQ = (LBG, LMP)\n| &&
|NCN = (GGR, VCX)\n| &&
|PBN = (FNP, CCG)\n| &&
|SQD = (BMK, RPT)\n| &&
|QKR = (KKD, XSD)\n| &&
|DTJ = (DGX, LPB)\n| &&
|TSJ = (GNR, FKQ)\n| &&
|TVC = (FGC, QBT)\n| &&
|NCC = (RGL, KGL)\n| &&
|DVT = (CRX, RQK)\n| &&
|THL = (PKL, PNH)\n| &&
|QQM = (VMJ, VJS)\n| &&
|DKR = (NCN, HQJ)\n| &&
|MKF = (VLR, LQS)\n| &&
|VFS = (CFF, JJL)\n| &&
|GDF = (GFD, GPH)\n| &&
|DQF = (RVR, KMK)\n| &&
|NSX = (KLV, CLQ)\n| &&
|JGF = (TCV, QDH)\n| &&
|XKS = (PXL, CVB)\n| &&
|RSQ = (HQB, DMF)\n| &&
|DXX = (LFV, NTJ)\n| &&
|VKF = (MCV, MVT)\n| &&
|BDD = (DGX, LPB)\n| &&
|DNS = (PVR, CFK)\n| &&
|SRV = (RQC, JHM)\n| &&
|XDL = (QRG, BCL)\n| &&
|NCT = (KRK, NBF)\n| &&
|XQK = (THL, SVQ)\n| &&
|DLB = (HFT, TSF)\n| &&
|DVX = (CJF, NSJ)\n| &&
|NCR = (BSL, BRP)\n| &&
|CSV = (XRJ, VKF)\n| &&
|KLS = (TTS, VGR)\n| &&
|JCB = (BLM, TQL)\n| &&
|MXP = (NNG, XXS)\n| &&
|FNP = (PVB, GBB)\n| &&
|XGS = (GLK, GDT)\n| &&
|VBQ = (SRM, LHT)\n| &&
|GHQ = (SJG, CDX)\n| &&
|LQS = (JKR, XDX)\n| &&
|MXS = (HQJ, NCN)\n| &&
|MNN = (TKP, FBN)\n| &&
|DVR = (CVH, TRK)\n| &&
|VKQ = (HKQ, XHG)\n| &&
|KHX = (TSJ, NVT)\n| &&
|BMK = (SKB, JCB)\n| &&
|FGC = (HFQ, PGM)\n| &&
|TVD = (QKR, NQJ)\n| &&
|BNF = (CFJ, RBT)\n| &&
|NXN = (VKQ, JNR)\n| &&
|VJM = (CCS, KVL)\n| &&
|XRL = (QVM, KJC)\n| &&
|SRH = (XJJ, CDM)\n| &&
|FDF = (JNF, SXX)\n| &&
|XKM = (FDV, VTC)\n| &&
|BLQ = (CDT, CRD)\n| &&
|VMF = (QLC, HMF)\n| &&
|JGP = (LPS, JNC)\n| &&
|BVB = (HPT, LRQ)\n| &&
|LNR = (QFR, MDF)\n| &&
|VJR = (HHF, JQS)\n| &&
|FHQ = (MBC, QBQ)\n| &&
|SLM = (XJJ, CDM)\n| &&
|HVC = (LCR, NNL)\n| &&
|KNT = (XKM, VDF)\n| &&
|KGL = (NSH, TMK)\n| &&
|KNL = (GKD, SBM)\n| &&
|CJF = (VGN, SJD)\n| &&
|HXJ = (DMX, GFN)\n| &&
|RGR = (XTR, HNR)\n| &&
|PMP = (XDK, HLS)\n| &&
|TKB = (BLF, PSP)\n| &&
|VBJ = (RGL, KGL)\n| &&
|LCJ = (CDX, SJG)\n| &&
|JCM = (HKH, KDS)\n| &&
|CXD = (FTH, RFL)\n| &&
|TSF = (CXS, NXF)\n| &&
|BSL = (CCM, PFB)\n| &&
|QRC = (KPC, LJF)\n| &&
|MLD = (JGB, XMR)\n| &&
|CRR = (CRD, CDT)\n| &&
|GNJ = (KCN, KCN)\n| &&
|QRJ = (GVD, HJZ)\n| &&
|CDN = (SPF, MLD)\n| &&
|HLS = (VHT, XQX)\n| &&
|HML = (SBR, FMH)\n| &&
|RPT = (JCB, SKB)\n| &&
|SBM = (SSP, JSP)\n| &&
|VBN = (LTB, JST)\n| &&
|NBS = (FDF, MSG)\n| &&
|MDR = (GBQ, RSF)\n| &&
|XDM = (TGL, NLD)\n| &&
|SKB = (TQL, BLM)\n| &&
|NNL = (LXP, QTD)\n| &&
|KQM = (KLV, CLQ)\n| &&
|VLR = (JKR, XDX)\n| &&
|RSG = (LDQ, CPG)\n| &&
|LJH = (NMR, NMR)\n| &&
|RGK = (QQS, TMC)\n| &&
|SQN = (VVL, JFP)\n| &&
|DFP = (TKP, FBN)\n| &&
|SCP = (VGX, GCS)\n| &&
|VBP = (DMP, FXK)\n| &&
|NMV = (MSG, FDF)\n| &&
|QCF = (DXX, VLL)\n| &&
|HHT = (MKF, GBN)\n| &&
|SBZ = (DVT, DSH)\n| &&
|SNV = (PMP, FRM)\n| &&
|GQC = (KBM, DLT)\n| &&
|MQQ = (KVL, CCS)\n| &&
|VGP = (LXN, MVD)\n| &&
|GBN = (VLR, LQS)\n| &&
|MVX = (JFP, VVL)\n| &&
|DRX = (BTJ, FGM)\n| &&
|JRH = (XGJ, RSQ)\n| &&
|RVR = (TDT, TNF)\n| &&
|PVK = (QQM, JVV)\n| &&
|JQS = (XGS, FXR)\n| &&
|BCL = (RSG, QSL)\n| &&
|GBB = (MMK, CVT)\n| &&
|SSQ = (XND, DDQ)\n| &&
|PCC = (JHM, RQC)\n| &&
|CCS = (CDD, MBG)\n| &&
|MMP = (NBR, BJM)\n| &&
|MTJ = (QFD, CQD)\n| &&
|PVB = (CVT, MMK)\n| &&
|KLR = (TND, VMF)\n| &&
|FKX = (KHX, GQK)\n| &&
|FDV = (DKR, MXS)\n| &&
|TCB = (LHG, TQN)\n| &&
|JDK = (NXH, JVR)\n| &&
|GBQ = (SCP, JPT)\n| &&
|TTN = (GLB, CJJ)\n| &&
|JTF = (DVR, KDL)\n| &&
|QQQ = (TTN, GKM)\n| &&
|DXP = (LHH, CSF)\n| &&
|MFD = (BSS, PQJ)\n| &&
|PGN = (RJC, FSX)\n| &&
|MBF = (XKQ, MFB)\n| &&
|XXS = (FXT, GCB)\n| &&
|VGX = (VBJ, NCC)\n| &&
|FPJ = (PJP, RFZ)\n| &&
|XTG = (NMR, PQZ)\n| &&
|JGR = (XVL, KKJ)\n| &&
|MSG = (JNF, SXX)\n| &&
|CKQ = (PCN, CGD)\n| &&
|QSL = (LDQ, CPG)\n| &&
|XQL = (HPT, LRQ)\n| &&
|KVT = (TND, VMF)\n| &&
|BBX = (BNF, FQN)\n| &&
|CLJ = (QQR, RGR)\n| &&
|GSN = (VDJ, TJN)\n| &&
|DLT = (SXP, SFS)\n| &&
|XFD = (BVB, XQL)\n| &&
|FHL = (BKK, BKK)\n| &&
|FSX = (LGB, CNM)\n| &&
|SPQ = (KNP, GHG)\n| &&
|NXJ = (JXQ, PBK)\n| &&
|NPV = (CDN, KQX)\n| &&
|DPN = (CHL, NQN)\n| &&
|RMR = (HRC, KHL)\n| &&
|LPF = (XQG, QCD)\n| &&
|THT = (NDJ, NVK)\n| &&
|JNC = (PTK, PHC)\n| &&
|LGF = (XXS, NNG)\n| &&
|CVB = (CCL, GQG)\n| &&
|VVL = (RDJ, QHG)\n| &&
|LCR = (LXP, QTD)\n| &&
|PQJ = (TVJ, MKK)\n| &&
|VDF = (FDV, VTC)\n| &&
|GTG = (FRV, RQV)\n| &&
|FRM = (XDK, HLS)\n| &&
|LPB = (SPV, PNV)\n| &&
|NBF = (TTQ, CGX)\n| &&
|XKQ = (QTM, JTF)\n| &&
|BRP = (PFB, CCM)\n| &&
|KVD = (XKM, VDF)\n| &&
|XBJ = (GGF, JPG)\n| &&
|KDS = (GCC, SHP)\n| &&
|TVJ = (PSD, MTJ)\n| &&
|XSM = (NLJ, JRF)\n| &&
|BTS = (SKS, XQK)\n| &&
|VVS = (LRF, KXL)\n| &&
|SPV = (BMP, LLQ)\n| &&
|KQL = (BPD, NCB)\n| &&
|CGX = (MVF, HLJ)\n| &&
|XBM = (TPK, TPK)\n| &&
|TMK = (JTQ, SHX)\n| &&
|VNT = (DXX, VLL)\n| &&
|CBM = (QDH, TCV)\n| &&
|TQL = (QTP, FSN)\n| &&
|HKQ = (VVS, HTD)\n| &&
|RQC = (KQR, NLH)\n| &&
|FMH = (VMS, MSD)\n| &&
|NCB = (HRM, TPB)\n| &&
|BKK = (GNN, GNN)\n| &&
|QRG = (QSL, RSG)\n| &&
|JSP = (NSX, KQM)\n| &&
|RQP = (CRQ, QNQ)\n| &&
|JHR = (NJT, STV)\n| &&
|MXC = (MBF, FCQ)\n| &&
|LBV = (LVM, SSN)\n| &&
|KLV = (KFG, RCL)\n| &&
|FJM = (TXK, LCG)\n| &&
|QVX = (FMM, JTP)\n| &&
|LJF = (KLS, HTF)\n| &&
|QXH = (PFP, CLL)\n| &&
|KQR = (GFB, RTT)\n| &&
|MHN = (SBK, BBF)\n| &&
|GTH = (KFX, DSC)\n| &&
|GCP = (RVD, JQG)\n| &&
|CXS = (NGQ, JSQ)\n| &&
|BJM = (BXP, LSX)\n| &&
|LLQ = (NRD, FSK)\n| &&
|CSF = (RDP, KXM)\n| &&
|TXK = (CBS, PFV)\n| &&
|SXP = (TSC, BTS)\n| &&
|PQZ = (TJF, HXM)\n| &&
|KBM = (SXP, SFS)\n| &&
|HHF = (FXR, XGS)\n| &&
|TNV = (NLJ, JRF)\n| &&
|JST = (DTR, FKX)\n| &&
|XKC = (LJN, CQV)\n| &&
|TCS = (SVN, PGS)\n| &&
|PPC = (DGS, GSN)\n| &&
|LGB = (LGV, VBN)\n| &&
|MVT = (VDS, PBP)\n| &&
|TST = (XBJ, HLF)\n| &&
|QVM = (GPX, DBL)\n| &&
|NSJ = (SJD, VGN)\n| &&
|PFH = (SCF, CQH)\n| &&
|JTP = (FVF, CKQ)\n| &&
|QDF = (GHV, TKB)\n| &&
|TTS = (DRX, VQT)\n| &&
|CDT = (FXQ, TVC)\n| &&
|DCP = (SBM, GKD)\n| &&
|VPZ = (PLF, VQV)\n| &&
|NLD = (JTX, VMR)\n| &&
|HFT = (CXS, NXF)\n| &&
|GCS = (VBJ, NCC)\n| &&
|HHQ = (KMP, GQT)\n| &&
|RMT = (BDX, CVG)\n| &&
|TRC = (QVJ, KNF)\n| &&
|LPX = (DDQ, XND)\n| &&
|SQR = (HGN, GDF)\n| &&
|KFG = (MDC, FJM)\n| &&
|BGM = (RGK, QFB)\n| &&
|KKD = (TGJ, BDS)\n| &&
|LFV = (PKQ, NGP)\n| &&
|GPS = (LPS, JNC)\n| &&
|CGJ = (MVX, SQN)\n| &&
|DGX = (SPV, PNV)\n| &&
|KMK = (TDT, TNF)\n| &&
|BVS = (VQM, FPJ)\n| &&
|MDC = (TXK, LCG)\n| &&
|KMN = (CJF, NSJ)\n| &&
|QHG = (QQQ, NGC)\n| &&
|KXL = (VJM, MQQ)\n| &&
|BMB = (SVN, PGS)\n| &&
|NLJ = (LNR, HSF)\n| &&
|TSC = (XQK, SKS)\n| &&
|JRX = (KDS, HKH)\n| &&
|TND = (QLC, HMF)\n| &&
|QCD = (LQK, GXD)\n| &&
|NRD = (LCX, LPF)\n| &&
|HXP = (PQJ, BSS)\n| &&
|HLJ = (MNN, DFP)\n| &&
|MNT = (CFP, FGB)\n| &&
|KSG = (MVD, LXN)\n| &&
|FPN = (FHQ, GBD)\n| &&
|HXM = (SRH, SLM)\n| &&
|CLQ = (KFG, RCL)\n| &&
|XGJ = (DMF, HQB)\n| &&
|FSK = (LPF, LCX)\n| &&
|GDL = (HHR, XKC)\n| &&
|PTF = (XDM, GDD)\n| &&
|AAA = (PQP, VBQ)\n| &&
|XDX = (MDR, NKN)\n| &&
|SMX = (RQP, DQJ)\n| &&
|LBP = (RHG, MMP)\n| &&
|FQN = (RBT, CFJ)\n| &&
|KDL = (CVH, TRK)\n| &&
|QCA = (HXM, TJF)\n| &&
|MVD = (GBC, DKT)\n| &&
|FMK = (FQL, PSR)\n| &&
|PMX = (SNV, HPJ)\n| &&
|GLK = (XVD, DNS)\n| &&
|NJT = (DXP, XHQ)\n| &&
|SML = (RRH, PTF)\n| &&
|BMP = (NRD, FSK)\n| &&
|QKN = (MNT, JCQ)\n| &&
|QQK = (SPQ, LKJ)\n| &&
|JDR = (GHV, TKB)\n| &&
|DMX = (FHL, FHL)\n| &&
|PMC = (NXP, GLC)\n| &&
|HSF = (QFR, MDF)\n| &&
|NDJ = (PMC, VRF)\n| &&
|JMG = (SBR, FMH)\n| &&
|KHL = (NPH, VCR)\n| &&
|QTD = (BBX, TQP)\n| &&
|XHQ = (LHH, CSF)\n| &&
|GGF = (DLP, MMQ)\n| &&
|QDH = (TKL, LDF)\n| &&
|DMP = (MSB, TVD)\n| &&
|BLM = (QTP, FSN)\n| &&
|DBF = (QCR, GTG)\n| &&
|XNQ = (QQK, GLR)\n| &&
|HLQ = (MKF, GBN)\n| &&
|VDS = (DDV, THT)\n| &&
|LVG = (XNP, DXD)\n| &&
|STV = (XHQ, DXP)\n| &&
|KPC = (HTF, KLS)\n| &&
|FTH = (VMX, DBF)\n| &&
|KJC = (DBL, GPX)\n| &&
|PJP = (SMR, KKR)\n| AT |\n| INTO TABLE result.
  ENDMETHOD.
ENDCLASS.
